//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIMIC.PatientsService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PatientsService.PatientsServiceSoap")]
    public interface PatientsServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectPatients", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MIMIC.PatientsService.Patients SelectPatients(MIMIC.PatientsService.Patients patients);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchPatients", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable SearchPatients();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Patients : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int subject_idField;
        
        private int hadm_idField;
        
        private string insuranceField;
        
        private string languageField;
        
        private string genderField;
        
        private int ageField;
        
        private string religionField;
        
        private string marital_statusField;
        
        private string ethnicityField;
        
        private string dobField;
        
        private string dodField;
        
        private string dod_hospField;
        
        private string dod_ssnField;
        
        private int expire_flagField;
        
        private string admittimeField;
        
        private string dischtimeField;
        
        private string deathtimeField;
        
        private string admission_typeField;
        
        private string admission_locationField;
        
        private string discharge_locationField;
        
        private string edregtimeField;
        
        private string edouttimeField;
        
        private string diagnosisField;
        
        private int hospital_expire_flagField;
        
        private int has_chartevents_dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int subject_id {
            get {
                return this.subject_idField;
            }
            set {
                this.subject_idField = value;
                this.RaisePropertyChanged("subject_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int hadm_id {
            get {
                return this.hadm_idField;
            }
            set {
                this.hadm_idField = value;
                this.RaisePropertyChanged("hadm_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string insurance {
            get {
                return this.insuranceField;
            }
            set {
                this.insuranceField = value;
                this.RaisePropertyChanged("insurance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("language");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
                this.RaisePropertyChanged("gender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int age {
            get {
                return this.ageField;
            }
            set {
                this.ageField = value;
                this.RaisePropertyChanged("age");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string religion {
            get {
                return this.religionField;
            }
            set {
                this.religionField = value;
                this.RaisePropertyChanged("religion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string marital_status {
            get {
                return this.marital_statusField;
            }
            set {
                this.marital_statusField = value;
                this.RaisePropertyChanged("marital_status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ethnicity {
            get {
                return this.ethnicityField;
            }
            set {
                this.ethnicityField = value;
                this.RaisePropertyChanged("ethnicity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string dob {
            get {
                return this.dobField;
            }
            set {
                this.dobField = value;
                this.RaisePropertyChanged("dob");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string dod {
            get {
                return this.dodField;
            }
            set {
                this.dodField = value;
                this.RaisePropertyChanged("dod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string dod_hosp {
            get {
                return this.dod_hospField;
            }
            set {
                this.dod_hospField = value;
                this.RaisePropertyChanged("dod_hosp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string dod_ssn {
            get {
                return this.dod_ssnField;
            }
            set {
                this.dod_ssnField = value;
                this.RaisePropertyChanged("dod_ssn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int expire_flag {
            get {
                return this.expire_flagField;
            }
            set {
                this.expire_flagField = value;
                this.RaisePropertyChanged("expire_flag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string admittime {
            get {
                return this.admittimeField;
            }
            set {
                this.admittimeField = value;
                this.RaisePropertyChanged("admittime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string dischtime {
            get {
                return this.dischtimeField;
            }
            set {
                this.dischtimeField = value;
                this.RaisePropertyChanged("dischtime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string deathtime {
            get {
                return this.deathtimeField;
            }
            set {
                this.deathtimeField = value;
                this.RaisePropertyChanged("deathtime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string admission_type {
            get {
                return this.admission_typeField;
            }
            set {
                this.admission_typeField = value;
                this.RaisePropertyChanged("admission_type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string admission_location {
            get {
                return this.admission_locationField;
            }
            set {
                this.admission_locationField = value;
                this.RaisePropertyChanged("admission_location");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string discharge_location {
            get {
                return this.discharge_locationField;
            }
            set {
                this.discharge_locationField = value;
                this.RaisePropertyChanged("discharge_location");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string edregtime {
            get {
                return this.edregtimeField;
            }
            set {
                this.edregtimeField = value;
                this.RaisePropertyChanged("edregtime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string edouttime {
            get {
                return this.edouttimeField;
            }
            set {
                this.edouttimeField = value;
                this.RaisePropertyChanged("edouttime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string diagnosis {
            get {
                return this.diagnosisField;
            }
            set {
                this.diagnosisField = value;
                this.RaisePropertyChanged("diagnosis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public int hospital_expire_flag {
            get {
                return this.hospital_expire_flagField;
            }
            set {
                this.hospital_expire_flagField = value;
                this.RaisePropertyChanged("hospital_expire_flag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public int has_chartevents_data {
            get {
                return this.has_chartevents_dataField;
            }
            set {
                this.has_chartevents_dataField = value;
                this.RaisePropertyChanged("has_chartevents_data");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PatientsServiceSoapChannel : MIMIC.PatientsService.PatientsServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PatientsServiceSoapClient : System.ServiceModel.ClientBase<MIMIC.PatientsService.PatientsServiceSoap>, MIMIC.PatientsService.PatientsServiceSoap {
        
        public PatientsServiceSoapClient() {
        }
        
        public PatientsServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PatientsServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PatientsServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PatientsServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public MIMIC.PatientsService.Patients SelectPatients(MIMIC.PatientsService.Patients patients) {
            return base.Channel.SelectPatients(patients);
        }
        
        public System.Data.DataTable SearchPatients() {
            return base.Channel.SearchPatients();
        }
    }
}
